#!/usr/bin/env bash

set -eo pipefail

# This file is a pre-build hook executed by mod_wsgi-docker
# More info on hooks at:
# https://github.com/GrahamDumpleton/mod_wsgi-docker/blob/master/2.7/build.sh

# Add the current directory (/app) to requirements.txt
# This causes mod_wsgi_docker to install the local directory with pip
echo "-e ." >> /app/requirements.txt

# Copy application.wsgi into the location mod-wsgi_docker expects it
cp /app/deploy/application.wsgi /app/ga4gh/

echo " -----> Installing extra libs"
apt-get update && \
	apt-get install -y --no-install-recommends \
	libffi-dev \
	libxslt1-dev
